# Generated by Django 4.1.7 on 2023-02-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="Code")),
                (
                    "unit_class",
                    models.CharField(max_length=10, verbose_name="Unit Class"),
                ),
                (
                    "is_metric",
                    models.BooleanField(
                        default=True, verbose_name="Is Metric?"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "print_symbol",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Print Symbol",
                    ),
                ),
                (
                    "unit_property",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Unit Property",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "unit_value",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Value",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
            },
        ),
    ]
