name: Code Compliance

on:
  pull_request:
  push:
    branches: [main, dev]

jobs:
  code-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - run: pipenv install --dev

      - name: pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Testing and Coverage
        run: pipenv run pytest
